# [global]
# Configurações globais do Streamlit.
# showWarningOnDirectExecution: Esconde avisos ao executar scripts diretamente.

# [server]
# Configurações do servidor Streamlit.
# runOnSave: Reinicia o app ao salvar arquivos.
# port: Porta em que o servidor será executado.

# [browser]
# Configurações relacionadas ao navegador.
# gatherUsageStats: Desativa coleta de estatísticas de uso.

# [theme]
# Personalização do tema visual do app.
# primaryColor: Cor principal.
# backgroundColor: Cor de fundo.
# secondaryBackgroundColor: Cor de fundo secundária.
# textColor: Cor do texto.

# [ui]
# Configurações da interface do usuário.
# hideTopBar: Esconde a barra superior.
# hideSidebarNav: Esconde ou mostra a navegação lateral.

[global]
showWarningOnDirectExecution = false

[server]
runOnSave = true
port = 8501

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#1a8c73"
backgroundColor = "#f8f9fa"
secondaryBackgroundColor = "#ffffff"
textColor = "#262730"

[ui]
hideTopBar = true
